#!/usr/bin/env python3
"""Stamp true intrinsic width/height onto every local <img> in site/.

Without width/height the browser can't reserve space for an image before it
downloads, so pages jump as they load and loading="lazy" has nothing to go
on: every image downloads at once. The attributes only set the aspect ratio
the layout reserves; the CSS (img { max-width:100%; height:auto }) still
decides the rendered size.

Reads sizes straight from the file headers (WebP, PNG, JPEG), no dependencies.

Usage:
  python3 scripts/stamp_image_sizes.py          # write missing/wrong sizes
  python3 scripts/stamp_image_sizes.py --check  # CI: fail if any are missing/wrong
"""
import re, struct, sys, urllib.parse
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SITE = ROOT / "site"
SKIP_DIRS = {"blog", "experiments"}   # blog isn't deployed; experiments are hand-built demos
# Generated by build_work_index.py (its cards already reserve space with CSS aspect-ratio).
SKIP_FILES = {"work/index.html"}

IMG = re.compile(r"<img\b[^>]*>", re.I)
ATTR = lambda name: re.compile(r'\s%s="([^"]*)"' % name, re.I)
SRC, DATA_SRC, WIDTH, HEIGHT = ATTR("src"), ATTR("data-src"), ATTR("width"), ATTR("height")


def image_size(path):
    b = path.read_bytes()[:64 * 1024]
    if b[:4] == b"RIFF" and b[8:12] == b"WEBP":
        kind = b[12:16]
        if kind == b"VP8X":
            return 1 + int.from_bytes(b[24:27], "little"), 1 + int.from_bytes(b[27:30], "little")
        if kind == b"VP8 ":
            w, h = struct.unpack("<HH", b[26:30])
            return w & 0x3FFF, h & 0x3FFF
        if kind == b"VP8L":
            n = int.from_bytes(b[21:25], "little")
            return (n & 0x3FFF) + 1, ((n >> 14) & 0x3FFF) + 1
    if b[:8] == b"\x89PNG\r\n\x1a\n":
        return struct.unpack(">II", b[16:24])
    if b[:2] == b"\xff\xd8":
        i = 2
        while i + 9 < len(b):
            if b[i] != 0xFF:
                i += 1
                continue
            marker, seglen = b[i + 1], struct.unpack(">H", b[i + 2:i + 4])[0]
            if 0xC0 <= marker <= 0xCF and marker not in (0xC4, 0xC8, 0xCC):
                h, w = struct.unpack(">HH", b[i + 5:i + 9])
                return w, h
            i += 2 + seglen
    return None


def resolve(html_path, src):
    if not src or re.match(r"^(https?:|data:|//)", src):
        return None
    src = urllib.parse.unquote(src.split("?")[0].split("#")[0])
    p = (SITE / src.lstrip("/")) if src.startswith("/") else (html_path.parent / src)
    return p if p.is_file() else None


def process(html_path, check):
    text = html_path.read_text(encoding="utf-8")
    problems = []

    def fix(m):
        tag = m.group(0)
        src = (SRC.search(tag) or DATA_SRC.search(tag))
        f = resolve(html_path, src.group(1)) if src else None
        size = image_size(f) if f else None
        if not size:
            return tag
        w, h = size
        cw, ch = WIDTH.search(tag), HEIGHT.search(tag)
        if cw and ch and cw.group(1) == str(w) and ch.group(1) == str(h):
            return tag
        problems.append(f"{html_path.relative_to(SITE)}: {src.group(1)} -> {w}x{h}")
        tag = WIDTH.sub("", HEIGHT.sub("", tag))
        return tag[:4] + f' width="{w}" height="{h}"' + tag[4:]

    new = IMG.sub(fix, text)
    if not check and new != text:
        html_path.write_text(new, encoding="utf-8")
    return problems


def main():
    check = "--check" in sys.argv
    pages = [p for p in sorted(SITE.rglob("*.html"))
             if not SKIP_DIRS.intersection(p.relative_to(SITE).parts)
             and p.relative_to(SITE).as_posix() not in SKIP_FILES]
    problems = [x for p in pages for x in process(p, check)]
    if check:
        if problems:
            print(f"{len(problems)} image(s) missing correct width/height, e.g.:")
            print("\n".join(problems[:15]))
            print("Run: python3 scripts/stamp_image_sizes.py")
            sys.exit(1)
        print("All local images have width/height.")
    else:
        print(f"Stamped {len(problems)} image(s) across {len(pages)} page(s).")


if __name__ == "__main__":
    main()
